/**
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144,
By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
*/

fn main() {
    let mut pt1 = 0;
    let mut pt2 = 1;

    let top = 4000000;
    // print!("{}, {}, ", pt1, pt2);
    let mut sum:u64 = 0;
    let mut next = 0;

    let mut done = false;
    while !done {

        next = pt1+pt2;
        //Check our run condition
        done = next > top;

        //Shuffle!
        pt1 = pt2;
        pt2 = next;

        if next % 2 == 0 {
            sum+=next;
        }
        print!("{}, ",next);

    }
    println!("\nDone: {}",sum);
}
